### ISSUE TITLE
Могу выложить свои исходники для неона

### ISSUE THREAD

**Issue by mikelgusev** [troosh/pk11-16#1]
Архиваторы и все такое

**Comment by nzeemin** [comment]
@mikelgusev Конечно выкладывайте, всё что есть.

**Comment by mikelgusev** [comment]
https://github.com/mikelgusev/pdp11
если еще что нить найду выложу... где мог перевел из альта в читаемое

**Comment by nzeemin** [comment]
Спасибо вам большое, будем изучать.
Выложил ссылку на тематический форум, там есть специалисты: https://zx-pk.ru/threads/34832-iskhodniki-dlya-soyuz-neon-pk-11-16-ot-mikel-gusev.html

**Comment by troosh** [comment]
Спасибо, что поделились!
